DROP TABLE IF EXISTS player_stats;

CREATE TABLE player_stats(
 	season INT,
	full_name VARCHAR(255),
	team_id INT,
	player_id INT,
	team_name VARCHAR(255),
	pos VARCHAR(5),
	assists INT,
	putouts INT,
	errors INT,
	chances INT,
	fielding FLOAT,
	innings FLOAT,
	games INT,
	games_started INT,
	double_plays INT,
	triple_plays INT,
	throwing_errors INT,
	ground_outs INT,
	air_outs INT,
	runs INT,
	doubles INT,
	triples INT,
	home_runs INT,
	strike_outs INT,
	base_on_balls INT,
	intentional_walks INT,
	average FLOAT,
	at_bats INT,
	obp FLOAT,
	slg FLOAT,
	ops FLOAT,
	stolen_bases INT,
	caught_stealing INT,
	ground_into_double_play INT,
	number_of_pitches INT,
	plate_appearances INT,
	total_bases INT,
	rbi INT,
	left_on_base INT,
	sac_bunts INT,
	sac_flies INT,
	pitched_ground_outs INT,
	pitched_air_outs INT,
	pitched_runs INT,
	pitched_doubles INT,
	pitched_triples INT,
	pitched_home_runs INT,
	pitched_strike_outs INT,
	pitched_base_on_balls INT,
	pitched_intentional_walks INT,
	pitched_hits INT,
	pitcher_average FLOAT,
	saves INT,
	save_opportunities INT,
	holds INT,
	blown_saves INT,
	earned_runs INT,
	whip FLOAT,
	batters_faced INT,
	outs INT,
	games_pitched INT,
	complete_games INT,
	shutouts INT,
	pitcher_strikes INT,
	hit_batsmen INT,
	balks INT,
	wild_pitches INT,
	pickoffs INT,
	pitched_total_bases INT,
	pitches_per_inning FLOAT,
	games_finished INT,
	walks_per_9_inn FLOAT,
	inherited_runners INT,
	inherited_runners_scored INT,
	pitched_sac_bunts INT,
	pitched_sac_flies INT
);


--Creates joined table with duplicated rows, taken to python for final ETL
SELECT p.player_id,
	s.player,
	s.pos,
	p.team_id,
	p.team_name,
	p.season,
	s.salary,
	s.pct,
	s.warp,
	s.warpmil,
	s.dollarwarp,
	p.assists,
	p.putouts,
	p.errors,
	p.chances,
	p.fielding,
	p.innings,
	p.games,
	p.games_started,
	p.double_plays,
	p.triple_plays,
	p.throwing_errors,
	p.ground_outs,
	p.air_outs,
	p.runs,
	p.doubles,
	p.triples,
	p.home_runs,
	p.strike_outs,
	p.base_on_balls,
	p.intentional_walks,
	p.average,
	p.at_bats,
	p.obp,
	p.slg,
	p.ops,
	p.stolen_bases,
	p.caught_stealing,
	p.ground_into_double_play,
	p.number_of_pitches,
	p.plate_appearances,
	p.total_bases,
	p.rbi,
	p.left_on_base,
	p.sac_bunts,
	p.sac_flies,
	p.pitched_ground_outs,
	p.pitched_air_outs,
	p.pitched_runs,
	p.pitched_doubles,
	p.pitched_triples,
	p.pitched_home_runs,
	p.pitched_strike_outs,
	p.pitched_base_on_balls,
	p.pitched_intentional_walks,
	p.pitched_hits,
	p.pitcher_average,
	p.saves,
	p.save_opportunities,
	p.holds,
	p.blown_saves,
	p.earned_runs,
	p.whip,
	p.batters_faced,
	p.outs,
	p.games_pitched,
	p.complete_games,
	p.shutouts,
	p.pitcher_strikes,
	p.hit_batsmen,
	p.balks,
	p.wild_pitches,
	p.pickoffs,
	p.pitched_total_bases,
	p.pitches_per_inning,
	p.games_finished,
	p.walks_per_9_inn,
	p.inherited_runners,
	p.inherited_runners_scored,
	p.pitched_sac_bunts,
	p.pitched_sac_flies
INTO completed_stats
FROM player_salaries AS s
INNER JOIN player_stats AS p
ON ((s.player = p.full_name) AND (s.team = p.team_name) AND (s.year = p.season))
WHERE s.year != '2020';


--Creates cleaned joined table, with no duplicated rows
--Created temp table just in case
DROP TABLE IF EXISTS completed_stats_temp;
CREATE TABLE completed_stats_temp(
	player_id INT,
	full_name VARCHAR(255),
	pos VARCHAR(5),
	team_id INT,
	team_name VARCHAR(255),
	season INT,
	salary INT,
	pct FLOAT,
	warp FLOAT,
	warpmil FLOAT,
	dollarwarp FLOAT,
	assists FLOAT,
	putouts FLOAT,
	errors FLOAT,
	chances FLOAT,
	fielding FLOAT,
	innings FLOAT,
	games FLOAT,
	games_started FLOAT,
	double_plays FLOAT,
	triple_plays FLOAT,
	throwing_errors FLOAT,
	ground_outs FLOAT,
	air_outs FLOAT,
	runs FLOAT,
	doubles FLOAT,
	triples FLOAT,
	home_runs FLOAT,
	strike_outs FLOAT,
	base_on_balls FLOAT,
	intentional_walks FLOAT,
	average FLOAT,
	at_bats FLOAT,
	obp FLOAT,
	slg FLOAT,
	ops FLOAT,
	stolen_bases FLOAT,
	caught_stealing FLOAT,
	ground_into_double_play FLOAT,
	number_of_pitches FLOAT,
	plate_appearances FLOAT,
	total_bases FLOAT,
	rbi FLOAT,
	left_on_base FLOAT,
	sac_bunts FLOAT,
	sac_flies FLOAT,
	pitched_ground_outs FLOAT,
	pitched_air_outs FLOAT,
	pitched_runs FLOAT,
	pitched_doubles FLOAT,
	pitched_triples FLOAT,
	pitched_home_runs FLOAT,
	pitched_strike_outs FLOAT,
	pitched_base_on_balls FLOAT,
	pitched_intentional_walks FLOAT,
	pitched_hits FLOAT,
	pitcher_average FLOAT,
	saves FLOAT,
	save_opportunities FLOAT,
	holds FLOAT,
	blown_saves FLOAT,
	earned_runs FLOAT,
	whip FLOAT,
	batters_faced FLOAT,
	outs FLOAT,
	games_pitched FLOAT,
	complete_games FLOAT,
	shutouts FLOAT,
	pitcher_strikes FLOAT,
	hit_batsmen FLOAT,
	balks FLOAT,
	wild_pitches FLOAT,
	pickoffs FLOAT,
	pitched_total_bases FLOAT,
	pitches_per_inning FLOAT,
	games_finished FLOAT,
	walks_per_9_inn FLOAT,
	inherited_runners FLOAT,
	inherited_runners_scored FLOAT,
	pitched_sac_bunts FLOAT,
	pitched_sac_flies FLOAT
);

--Dropped original and replaced with temp
DROP TABLE completed_stats;
ALTER TABLE completed_stats_temp
RENAME TO completed_stats;

